### ISSUE TITLE
点击“直链下载”之后，网页长时间显示“请求中”

### ISSUE THREAD

**Issue by Hollowintheshell** [proxyee-down-org/proxyee-down#1022]
### 问题描述(必要)
选择文件并点击“直链下载”之后，网页长时间显示“请求中”，然后ProxyeeDown一直没有出现任务；
选择“批量推送下载”则长时间显示“正在推送中，请勿关闭浏览器”，然后也没有建立任务
### 版本号(必要)
当前版本： 3.32
### 操作系统(必要)
Windows7
### 相关截图
![default](https://user-images.githubusercontent.com/44747911/47964990-f1600080-e07b-11e8-91e5-decf94c766cf.png)

### 相关日志
2018-11-04 20:15:11.786 [nioEventLoopGroup-3-1] ERROR org.pdown.gui.http.EmbedHttpServer - native request error
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by 14SHIKE** [comment]
选择批量推送，可以通过重新解压3.32压缩包来重置设置
也可以试试存盘后重新分享链接
压缩包链接
https://imhx-my.sharepoint.com/:f:/g/personal/pd_imhx_onmicrosoft_com/EnPrybHS3rVFuy_HdcP7RLoBwhb0k5ayJdIzwjU0hCM9-A?e=he0oIz
