### ISSUE TITLE
FIREFOX63 無PD按鈕

### ISSUE THREAD

**Issue by kai456789** [proxyee-down-org/proxyee-down#1131]
### 问题描述(必要)
FIREFOX63 已導入證書 無PD按鈕 想在SWITCH OMEGA設定PAC模式 顯示技術問題不支援
FIREFOX本身的網路代理設定 也無PAC可填
### 版本号(必要)
3.4
### 操作系统(必要)
W7 
### 相关日志
[nioEventLoopGroup-3-1] ERROR org.pdown.gui.http.EmbedHttpServer - native request error
java.io.IOException: 遠端主機已強制關閉一個現存的連線。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by monkeyWie** [comment]
可以直接把pac链接粘贴到火狐的pac代理设置里
![image](https://user-images.githubusercontent.com/13160176/49483713-317af480-f86f-11e8-84af-2a6322edc7ef.png)
