### ISSUE TITLE
百度云下载过了一会儿会就会失败

### ISSUE THREAD

**Issue by Aithosa** [proxyee-down-org/proxyee-down#1175]
### 问题描述(必要)
<br>我用百度云下载扩展插件下载文件是，选择直链下载，一开始很正常，下一会就会显示下载失败，然后我刷新一下任务又会正常，重复几次后就算刷新也不会有下载进度了，一直显示失败。但是我百度网盘应用还能下载，一如既往的只有几十kb/s。
### 版本号(必要)
3.4
### 操作系统(必要)
win10家庭版
### 相关截图
![2018-12-23 1](https://user-images.githubusercontent.com/32020141/50381089-93818980-06b8-11e9-9e71-d4bcc0599343.png)
### 相关日志
```log
2018-12-22 22:04:31.037 [nioEventLoopGroup-3-2] ERROR org.pdown.gui.http.EmbedHttpServer - native request error
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2018-12-22 22:04:31.037 [nioEventLoopGroup-3-1] ERROR org.pdown.gui.http.EmbedHttpServer - native request error
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2018-12-22 22:08:24.897 [nioEventLoopGroup-3-2] ERROR org.pdown.gui.http.EmbedHttpServer - native request error
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Cloud989** [comment]
I don't know why I can not input Chinese here??
But I also have this kind of problem. The download speed is unstable and always fails (ps: the network connection is in good condition). Please help us to find a solution.

**Comment by luzy99** [comment]
应该是下载速度太快被百度查到封号了，我也是这样，换了个账号刷新了一下链接就好了。我试了一下限速1mb就没问题

**Comment by Aithosa** [comment]
> 应该是下载速度太快被百度查到封号了，我也是这样，换了个账号刷新了一下链接就好了。我试了一下限速1mb就没问题

不太清楚到底封的是什么，按理说下载文件没有用到我的百度账户信息，而且我的百度云客户端还正常，所以封的应该不是我的账号，也应该不是ip。。。我用别的插件提取到文件下载地址时直接复制过去会提示响应码异常，只能直接的点击下载然后用弹出的PD选项下载，才能正常创建任务，那几天只能用官方客户端下载简直憋死我了，百度太恶心了。。。

**Comment by Long-biao** [comment]
> 应该是下载速度太快被百度查到封号了，我也是这样，换了个账号刷新了一下链接就好了。我试了一下限速1mb就没问题

我被封了两个号了，具体要限速多少？

**Comment by Wmdht** [comment]
我也是 我后来用2.33版本再试了试，发现分段64的情况下，一次只会同时下载2~4个分段，而且这几个分段下完了就会显示下载失败，必须重新刷新才行。（不是刷新链接，就只是单纯的点一下继续）

**Comment by Wmdht** [comment]
2.33和2.54都是如此，3.12和3.4不显示这些东西也没看，不过应该也是一样的。
