### ISSUE TITLE
WIN10下下载Baidu网盘失败

### ISSUE THREAD

**Issue by daltonwang** [proxyee-down-org/proxyee-down#1241]
### 问题描述(必要)
安装了PD和扩展，在Chrome环境下关闭了其他扩展之后，能看到PD
### 版本号(必要)
3.4
### 操作系统(必要)
WIN10 64BIT
### 相关截图
![image](https://user-images.githubusercontent.com/4149227/53295199-28c40a00-3831-11e9-9fb4-3b7515fd00ea.png)

### 相关日志
2019-02-24 12:30:08.429 [nioEventLoopGroup-3-2] ERROR org.pdown.gui.http.EmbedHttpServer - native request error
java.io.IOException: Ô¶³ÌÖ÷»úÇ¿ÆÈ¹Ø±ÕÁËÒ»¸öÏÖÓÐµÄÁ¬½Ó¡£
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by CRO2017** [comment]
我也是，不过开发者貌似几百年没跟这个project了，快回来啊大佬555
