### ISSUE TITLE
百度云直接下载持续失败，替换任务数次均失败。

### ISSUE THREAD

**Issue by kentkwan** [proxyee-down-org/proxyee-down#1249]
### 问题描述(必要)
百度云直接下载持续失败，替换任务数次均失败。
### 版本号(必要)
3.4
### 操作系统(必要)
macOS Mojave 10.14.3
### 相关日志
2019-03-04 15:15:22.923 [JavaFX Application Thread] ERROR org.pdown.gui.DownApplication - Extension content load error
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.pdown.gui.util.ExecUtil.httpGet(ExecUtil.java:80)
	at org.pdown.gui.extension.mitm.util.ExtensionProxyUtil.disabledProxy(ExtensionProxyUtil.java:105)
	at org.pdown.gui.extension.mitm.util.ExtensionProxyUtil.enabledPACProxy(ExtensionProxyUtil.java:51)
	at org.pdown.gui.util.AppUtil.refreshPAC(AppUtil.java:52)
	at org.pdown.gui.DownApplication.initExtension(DownApplication.java:159)
	at org.pdown.gui.DownApplication.start(DownApplication.java:92)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by FrankBindi** [comment]
出现同样问题，下载任务几秒钟就会停止，显示失败
操作系统macOS Mojave 10.14.3

**Comment by creanme** [comment]
同样问题，win10系统，版本3.4

**Comment by LemonGirl97** [comment]
同样问题，win10，版本3.4

**Comment by Alex-jojo** [comment]
同win10     3.4

**Comment by gongyongshun** [comment]
哎 作者已基本放弃维护了

**Comment by orchie** [comment]
看来度娘已经封了这个了... 默哀.

**Comment by gongyongshun** [comment]
还能用
