### ISSUE TITLE
文件下载完成，使用百度云解压工具解压失败

### ISSUE THREAD

**Issue by ss12789** [proxyee-down-org/proxyee-down#515]
### 问题描述(必要)
文件下载完成，使用百度云解压工具解压失败，提示修复失败,文件损坏请重新下载。同时下载的两个文件都这样。
### 版本号(必要)
2.43
### 操作系统(必要)
WIN10
### 相关日志
2018-07-06  15:23:17.484 [Thread-1288] ERROR lee.study.down.mvc.controller.HttpDownController - unzip error:
java.lang.RuntimeException: 修复失败,文件损坏请重新下载
	at lee.study.down.io.BdyZip.getNextFixedBdyZipEntry(BdyZip.java:113)
	at lee.study.down.io.BdyZip.getFixedEntryList(BdyZip.java:186)
	at lee.study.down.io.BdyZip.unzip(BdyZip.java:253)
	at lee.study.down.mvc.controller.HttpDownController.lambda$bdyUnzip$3(HttpDownController.java:204)
	at java.lang.Thread.run(Thread.java:748)

**Comment by monkeyWie** [comment]
更新到2.54版本再试试
