### ISSUE TITLE
下载速度很慢（不管文件大小）

### ISSUE THREAD

**Issue by guangliang** [proxyee-down-org/proxyee-down#608]
### 问题描述(必要)
最近2天下载速度很慢，平均只有20KB/s
### 版本号(必要)
2.54
### 操作系统(必要)
Windows10 1803
### 相关截图
![image](https://user-images.githubusercontent.com/1175442/44616764-559a6300-a888-11e8-94f6-7504cb1fa2d9.png)
### 相关日志
2018-08-25  16:52:57.086 [nioEventLoopGroup-7-1] ERROR lee.study.down.handle.HttpDownInitializer - down onChunkError:
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:373)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
2018-08-25  16:53:44.151 [nioEventLoopGroup-7-1] ERROR lee.study.down.handle.HttpDownInitializer - down onChunkError:
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:813)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:373)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xrmoon** [comment]
不少朋友也是一样的问题，限速很严重，百度这又折腾呢-就是吃相太难看

**Comment by zhezh** [comment]
我今天也是很慢,几十 一百k, 还以为自己网有问题呢

**Comment by operammm** [comment]
没速度了+1...
百度云又在搞事情

**Comment by Eisx11o** [comment]
下载好慢了，5Kb，百度云又在搞事情

**Comment by hy345** [comment]
同没速度……大部分连接都是0B/s，其他的是10K/s左右

**Comment by dabi3ng** [comment]
百度真是毒

**Comment by fanghuan27** [comment]
nj02cm01

**Comment by Blackcf** [comment]
不是软件问题，黑号了

**Comment by TrustTheBoy** [comment]
@Blackcf @dabi3ng @hy345 @Eisx11o @operammm @zhezh 可以尝试使用代理进行下载，速度会快很多

**Comment by zhezh** [comment]
真的6 从台湾或者从美国绕一圈回来,速度倒是快...

**Comment by hy345** [comment]
@TrustTheBoy 哇真的 谢谢大佬

**Comment by InoriHimea** [comment]
这百毒就是只限速大陆，现在就是基于aria2的还能有速度！

**Comment by ershazi1977** [comment]
我这几天也是这样。。换了个百度盘账号就恢复了。。可能之前号被黑了。

**Comment by tcwaily** [comment]
我这下载挺快的，感觉没什么影响，我用的2.54版本

**Comment by monkeyWie** [comment]
试试3.0版本
