### ISSUE TITLE
下载大文件失败

### ISSUE THREAD

**Issue by wangruoyao** [proxyee-down-org/proxyee-down#723]
### 相关截图   
![vi i_j 4ympd2cfll p 8ab](https://user-images.githubusercontent.com/11000684/45496441-05882f80-b7a8-11e8-9596-565b8fdbe214.png)

### 相关日志   2018-09-13  22:50:07.391 [nioEventLoopGroup-12-1] ERROR lee.study.down.handle.HttpDownInitializer - down onChunkError:
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:373)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wangruoyao** [comment]
{"error_code":31326,"error_msg":"user is not authorized, hitcode:122","error_info":"","request_id":6021474785063582631}

**Comment by monkeyWie** [comment]
升级3.0版本以上安装百度云扩展，详见https://github.com/proxyee-down-org/proxyee-down-extension/tree/master/baiduYun

**Comment by FreedomNeverDie** [comment]
> > 升级3.0版本以上安装百度云扩展，详见https://github.com/proxyee-down-org/proxyee-down-extension/tree/master/baiduYun
> 
> 不行的，是批量下载问题。

我也遇到同样的问题，用的还是老版本的proxyee, 请问如何解决？
