### ISSUE TITLE
proxyee-down 3.12 最新版添加任务，任务列表不显示

### ISSUE THREAD

**Issue by jianboy** [proxyee-down-org/proxyee-down#887]
### 问题描述(必要)
下载操作后，确实可以通过pd下载，但是下载列表没有任何数据
### 版本号(必要)
3.12
### 操作系统(必要)
win10
### 相关截图
![baiduhi_2018-10-7_2-9-20](https://user-images.githubusercontent.com/11532015/46574448-296d1880-c9d6-11e8-8a16-7431fa405e7c.png)

**Comment by hjdb88** [comment]
> 手动创建的任务吗？

我也是一样，3.12版本在macOS下手动创建任务成功后在列表中没有显示该任务，重新手动创建任务提示已存在

**Comment by jianboy** [comment]
@monkeyWie 对的，手动创建单个任务。

（1）任务列表没有下载队列
（2）磁盘，CPU太高。单个任务磁盘30M/s左右读写。 磁盘消耗非常大。

**Comment by jianboy** [comment]
```
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: ReferenceError: Can't find variable: vue
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:137)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1482)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:1003)
	at lee.study.down.gui.HttpDownApplication.lambda$null$1(HttpDownApplication.java:170)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)


```

**Comment by jianboy** [comment]
已经找到问题了：Can't find variable: vue

com.sun.webkit.dom这个包报错，那么切换到浏览器，不再使用java的webkit包就没问题。。所以问题就是：

**com.sun.webkit包不兼容vue**

**Comment by monkeyWie** [comment]
我这里win10是没问题的啊，不过还好能切浏览器UI模式
