### ISSUE TITLE
Deepin15.7 openjdk+openjfx无法运行

### ISSUE THREAD

**Issue by mxdlzg** [proxyee-down-org/proxyee-down#890]
### 问题描述(必要)
java -jar proxyee-down-main.jar 无法运行
### 版本号(必要)
proxyee-down 3.12
openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Debian-4)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Debian-4, mixed mode)

### 操作系统(必要)
Deepin 15.7
### 相关截图
![Uploading 深度截图_deepin-terminal_20181007234520.png…]()

### 相关日志
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
	at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 16 more

**Comment by monkeyWie** [comment]
看起来是openjfx没有安装好

**Comment by mxdlzg** [comment]
> 看起来是openjfx没有安装好

的确是openjfx的问题，deepin源里面是openjdk8的jfx，而默认安装了openjdk10却没有10的jfx，卸载openjdk10就可以了
