### ISSUE TITLE
java -jar proxyee-down-main.jar错误

### ISSUE THREAD

**Issue by huangtianxing** [proxyee-down-org/proxyee-down#935]
### 问题描述(必要)
下载了peoxyee-down-main.jar无法运行
### 版本号(必要)
proxyee-down-main.jar 3.2
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)

### 操作系统(必要)
ubuntu18.04
### 相关截图
![2018-10-19 07-33-04](https://user-images.githubusercontent.com/42471429/47189910-64296600-d371-11e8-85e1-cfe4ee6f3afd.png)

### 相关日志
tianxing@tianxing-X556UB:~/下载$ java -jar proxyee-down-main.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 15 more
tianxing@tianxing-X556UB:~/下载$

**Comment by dacade** [comment]
我也是，出现这个了

**Comment by huangtianxing** [comment]
已经解决了，用su -或sudo切换成root身份运行就行了，虽然我不知道是为什么

**Comment by huangtianxing** [comment]
已经解决了，用su -或sudo切换成root身份运行就行了，虽然我不知道是为什么
